/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectochat;
import java.io.*;
import java.net.*;
import javax.swing.*;
public class Servidor extends javax.swing.JApplet implements Runnable{
    
    @Override
    public void init() {
    
        try {
            initComponents();
            Thread hiloServidor=new Thread(this);
            hiloServidor.start();
    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaChat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        txtAreaChat.setColumns(20);
        txtAreaChat.setRows(5);
        jScrollPane1.setViewportView(txtAreaChat);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("- SERVIDOR -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaChat;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try
        {
            
            ServerSocket skServidor=new ServerSocket(8888);
            
            Socket skCliente;
            
            String nick,ip,message;
            
            Envio paq_recibido;
            txtAreaChat.append("Estoy funcionando");
            while(true)
            {
                
                skCliente=skServidor.accept();
                ObjectInputStream paq_datos=new ObjectInputStream(skCliente.getInputStream());
                paq_recibido=(Envio) paq_datos.readObject();
                nick=paq_recibido.getNick();
                ip=paq_recibido.getIp();
                message=paq_recibido.getMessage();
                
                txtAreaChat.append("\n"+nick+" : "+message+" Para : "+ip);
                
                Socket sendDestinatario =new Socket(ip,8888);
                ObjectOutputStream resend=new ObjectOutputStream(sendDestinatario.getOutputStream());
                resend.writeObject(paq_recibido);
                resend.close();
            }
        }catch(Exception ex)
        {
            txtAreaChat.append("\n ----Contacto se ha desconectado-----");
        }
    }
}
